### ISSUE TITLE
Call to Action: People interested in developing this out

### ISSUE THREAD

**Issue by Xe** [Xe/sylph#1]
Hello,

I have some code here that needs to be redone, redesigned and overall re-architected to be an effective private reverse-reverse proxy for small and medium sized users. Here are some things I want to make sure is a part of this:

- [ ] Full API with clients able to be created in Node, Ruby, Python and Go (any other languages are a plus)
- [ ] Chatops: discord/slack integrations
- [ ] Terraform support for route/group/whatever creation
- [ ] Command line interface with subcommands and the like:
  - [ ] setup
    - [ ] generate root ssl cert key
    - [ ] setup admin user
  - [ ] route management
  - [ ] user management
  - [ ] access control management 
  - [ ] backend management
  - [ ] token mangement

# Strawman plan

Four components: API, agent, cli and router

API will be written with Rails API. Postgres will be used for the database.

Twirp will be used to model out the API between all of the components.

Agent will be written in Go and use the client mode of [tun2](https://godoc.org/github.com/Xe/x/tun2).

Cli will be written in Go and use the api provided by API.

Router will be written in Go using [tun2](https://godoc.org/github.com/Xe/x/tun2) with the following modifications:

- Use IETF Quic for agent -> router communication
- Remove KCP
- Remove smux
- Use Go tracing better

## alpha roadmap

- users are able to perform all API actions
- everything works end to end
- routers can discover eachother via a privileged API
- automatic TLS via either let's encrypt or [localca](https://godoc.org/github.com/Xe/x/localca)
- [URL template](https://godoc.org/gopkg.in/olivere/elastic.v3/uritemplates) support for subpath routing

## beta roadmap

- organization support with routes being owned by organizations or users
- access control lists 
- middleware
  - oauth2
  - jwt/paseto
  - webhook based auth
  - rate limiting

## 1.0 roadmap

- alternative routing logic other than round-robin
  - weight backends based on latency, arbitrary numerical metrics and/or [phi accrual failure ratio](https://github.com/dgryski/go-failure)
- arbitrary logic in webassembly/lua
